version: '2'
services:
    demohipster-app:
        image: demohipster
        external_links:
            - demohipster-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demohipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demohipster-mysql:
        extends:
            file: mysql.yml
            service: demohipster-mysql
